### ISSUE TITLE
Synchronize filetype-specific (scoped) settings

### ISSUE THREAD

**Issue by mdekstrand** [atom-community/sync-settings#121]
Right now, sync-settings does not seem to synchronize any of the scoped settings used to configure per-filetype rules such as indent depth. These show up in `config.cson` like so:

```
".gradle.groovy.source":
  editor:
    tabLength: 4
    showIndentGuide: true
```

However, they do not appear on `atom.config.settings`. I do not know how to get or set all of them.
