### ISSUE TITLE
Diff view red/green colors don't match remove/add

### ISSUE THREAD

**Issue by 1951FDG** [atom-community/sync-settings#742]
**Describe the bug**
text in red should be green
text in green should be red

**To Reproduce**

1. Packages > Synchronize Settings > Check for updated backup
2. On notification message, Click 'View Diff' button

**Expected behavior**

- red is usually used to indicate line removed
- green is usually used to indicate line added

**Screenshots**
![image](https://user-images.githubusercontent.com/220168/162942374-25c080fc-da78-4968-90e6-a74805f78d94.png)

**Versions**
 - OS:  macOS 12.3.1 (21E258)
 - Atom: 1.60.0

**Additional context**
Using together with location package, https://atom.io/packages/sync-settings-git-location

**Comment by UziTech** [comment]
You can actually change this locally if you want open your Atom stylesheet (`Application: Open Your Stylesheet`) and change the color from there:

```less
@import 'ui-variables';

.sync-settings-diff-view {
	.local {
		color: @text-color-success;
	}

	.backup {
		color: @text-color-error;
	}
}
```
